# Generated by Django 5.0.1 on 2024-01-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='large_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='medium_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='small_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='xlarge_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='xxlarge_stock',
            field=models.IntegerField(default=0),
        ),
    ]
