# Generated by Django 5.0.1 on 2024-03-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_category', models.CharField(choices=[('Strength', 'Strength'), ('Mobility', 'Mobility'), ('Speed', 'Speed'), ('Power', 'Power'), ('Cardio', 'Cardio'), ('Nutrition', 'Nutrition')], max_length=50)),
                ('plan_file', models.FileField(upload_to='player_plans/')),
                ('plan_picture', models.ImageField(blank=True, null=True, upload_to='plan_images/')),
            ],
        ),
    ]
