# Generated by Django 5.0.1 on 2024-01-07 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(14)])),
                ('country_of_interest', models.CharField(choices=[('USA', 'United States of America'), ('IRE', 'Ireland'), ('SCT', 'Scotland'), ('ENG', 'England')], max_length=3)),
                ('school_of_interest', models.CharField(max_length=100)),
                ('rugby_history', models.TextField()),
                ('cover_letter', models.TextField()),
                ('country_of_residence', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
