# Generated by Django 5.0.1 on 2024-01-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0004_auto_20240107_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerentry',
            name='country_of_interest',
        ),
    ]
