# Generated by Django 5.0.1 on 2024-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_rename_level_school_school_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='level',
        ),
        migrations.AddField(
            model_name='school',
            name='school_level',
            field=models.CharField(choices=[('HS', 'High School'), ('CO', 'College')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
