# Generated by Django 5.0.1 on 2024-01-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0007_remove_school_level_school_school_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='education_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='rugby_coach',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='rugby_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='rugby_video_link',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
