# Generated by Django 5.0.1 on 2024-01-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0008_alter_school_education_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='color',
            field=models.CharField(default='#8b0000', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='rugby_image',
            field=models.ImageField(default='recruiting/generic-rugby.jpg', upload_to='school_images/'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_image',
            field=models.ImageField(default='recruiting/generic-school.jpg', upload_to='school_images/'),
        ),
    ]
