# Generated by Django 5.0.1 on 2024-01-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0010_alter_school_rugby_image_alter_school_school_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='rugby_image',
            field=models.ImageField(default='/media/school_images/generic-rugby.jpg', upload_to='school_images/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_image',
            field=models.ImageField(default='/media/school_images/generic-school.jpg', upload_to='school_images/'),
        ),
    ]
