# Generated by Django 5.0.1 on 2024-01-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0012_alter_school_rugby_image_alter_school_school_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='rugby_image',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_image',
        ),
        migrations.CreateModel(
            name='RugbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rugby_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.school')),
            ],
        ),
    ]
