# Generated by Django 5.0.1 on 2024-02-03 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecruitingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unseen", "Unseen"),
                            ("Pending", "Pending"),
                            ("Follow up", "Follow up"),
                            ("Complete", "Complete"),
                        ],
                        default="Unseen",
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(default="prop", max_length=50)),
                (
                    "age",
                    models.IntegerField(
                        default="12",
                        validators=[django.core.validators.MinValueValidator(12)],
                    ),
                ),
                ("origin_country", models.CharField(default="usa", max_length=50)),
                (
                    "destination_country",
                    models.CharField(
                        choices=[
                            ("United States", "United States"),
                            ("England", "England"),
                            ("Ireland", "Ireland"),
                            ("Scotland", "Scotland"),
                            ("Wales", "Wales"),
                        ],
                        default="United States",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
