# Generated by Django 5.0.1 on 2024-02-13 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_tourssubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanterburyKitSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unseen", "Unseen"),
                            ("Pending", "Pending"),
                            ("Follow up", "Follow up"),
                            ("Complete", "Complete"),
                        ],
                        default="Unseen",
                        max_length=20,
                    ),
                ),
                ("teamname", models.CharField(default="Firstfive RFC", max_length=100)),
                (
                    "teamsize",
                    models.IntegerField(
                        default="15",
                        validators=[django.core.validators.MinValueValidator(15)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
