# Generated by Django 5.0.1 on 2024-03-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_teamitemsubmission_team_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('problem_description', models.TextField()),
                ('status', models.CharField(choices=[('Unseen', 'Unseen'), ('Pending', 'Pending'), ('Follow up', 'Follow up'), ('Complete', 'Complete')], default='Unseen', max_length=20)),
            ],
        ),
    ]
