# Generated by Django 5.0.1 on 2024-03-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('design_description', models.TextField()),
                ('status', models.CharField(choices=[('Unseen', 'Unseen'), ('Pending', 'Pending'), ('Follow up', 'Follow up'), ('Complete', 'Complete')], default='Unseen', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('status', models.CharField(choices=[('Unseen', 'Unseen'), ('Pending', 'Pending'), ('Follow up', 'Follow up'), ('Complete', 'Complete')], default='Unseen', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cell', models.CharField(max_length=15)),
                ('help_details', models.TextField()),
                ('status', models.CharField(choices=[('Unseen', 'Unseen'), ('Pending', 'Pending'), ('Follow up', 'Follow up'), ('Complete', 'Complete')], default='Unseen', max_length=20)),
            ],
        ),
    ]
